"$schema" = 'https://starship.rs/config-schema.json'

# ── General Prompt Layout ──
# Left: user@host, kube context/namespace, git branch/status
# Right: execution time
# Newline, then path + prompt char
format = "$username$hostname$kubernetes$git_branch$git_status$aws$directory$cmd_duration $character "
add_newline = true

# ── Prompt Character ──
[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'
vicmd_symbol = '[V](bold yellow)'

# ── User / Host ──
[username]
style_user = "bold yellow"
style_root = "bold red"
format = "[$user]($style)@"
show_always = true

[hostname]
ssh_only = false
format = "[$hostname](bold cyan) "
trim_at = "."
disabled = false

# ── Directory ──
[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold blue"
read_only = " "

# ── Git ──
[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold purple"
staged = "[+](green)"
modified = "[!](yellow)"
deleted = "[✘](red)"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕${ahead_count}/${behind_count}"
format = "([$all_status$ahead_behind]($style)) "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold yellow"

# ── Kubernetes ──
[kubernetes]
symbol = "☸ "
format = '[\($symbol$context( \($namespace\))\)](bold blue) '
disabled = false

# ── Command Duration ──
[cmd_duration]
min_time = 500
format = "[⏱ $duration]($style)"
style = "bold green"

# ── Fill (push right side) ──
[fill]
symbol = " "

# ── Optional: AWS profile indicator ──
[aws]
format = "[$symbol($profile)(@$region)](bold orange) "
symbol = "  "
disabled = false
