general {
    lock_cmd = hyprlock  # Command to run for locking
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 600  # Lock after 10 minutes of inactivity
    on-timeout = hyprlock
}

listener {
    timeout = 900  # Turn off displays after 15 minutes
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}